version: 2

sources:
  - name: f1_data
    schema: team_f1
    tables:
      - name: raw_stints  
        identifier: raw_stints 
        
      - name: raw_drivers
        identifier: raw_drivers

      - name: raw_pit
        identifier: raw_pit

      - name: raw_laps
        identifier: raw_laps

      - name: raw_position
        identifier: raw_position

      - name: raw_sessions
        identifier: raw_sessions

      - name: raw_race_control
        identifier: raw_race_control

      - name: raw_weather
        identifier: raw_weather

      - name: raw_result
        identifier: raw_result